# Generated by Django 3.2 on 2021-04-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=30)),
                ('email', models.TextField(max_length=30)),
                ('phone', models.TextField(max_length=20)),
            ],
        ),
    ]
